name: ShellCheck

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get update -qq && sudo apt-get install -y shellcheck

      - name: Run ShellCheck on install.sh
        run: shellcheck --shell=bash scripts/install.sh

